Repository manito42/FrontEnd, pull requests merged in 2023-10, with the labels that each got.

#216 [todo] 멘토 활성화 시 필수 요소 확인 기능 추가
  42manito/src/components/Profile/Toggle.tsx
Labels: todo, fix

#214 [fix] 멘토링 모달 상태관리
  42manito/src/RTK/Slices/MentorConnect.ts
  42manito/src/components/Connect/ConnectModal.tsx
  42manito/src/components/Mentor/Modal.tsx
Labels: fix

#218 [refactor] 버튼 UI 통합
  42manito/src/Types/General/ButtonType.ts
  42manito/src/common/Button/Button.module.css
  42manito/src/common/Button/Button.stories.tsx
  42manito/src/common/Button/Button.tsx
  42manito/src/components/Connect/ConnectModal.tsx
  42manito/src/components/Mentor/Modal.tsx
  42manito/src/components/Reservation/NextProgressButton.tsx
  42manito/src/components/Reservation/Reservation.tsx
  42manito/src/components/Reservation/modal/FeedbackModal.tsx
  42manito/src/pages/Profile/[userId].tsx
  42manito/src/pages/ProfileUpdate/[userId].tsx
  42manito/src/styles/connect.css
  42manito/src/styles/mentor.css
  42manito/src/styles/profile.css
  42manito/src/styles/reservation.css
Labels: refactor

#219 [fix]: Login #202
  42manito/src/components/Layout/Header/index.tsx
  42manito/src/components/Layout/Layout.tsx
  42manito/src/utils/BaseQuery.ts
Labels: fix

#217 [fix] sidebar ui 변경
  42manito/.yarn/install-state.gz
  42manito/src/components/Layout/Header/components/Sidebar.tsx
  42manito/src/components/Layout/Header/index.tsx
  42manito/src/styles/layout.css
Labels: fix

#220 [Fix] #208,#206,#197
  42manito/src/RTK/Slices/ProfileUpdate.ts
  42manito/src/components/Profile/Update/CategoryUpdateMultiple.tsx
  42manito/src/components/Profile/Update/HashtagUpdateInput.tsx
  42manito/src/components/Reservation/modal/FeedbackModal.tsx
  42manito/src/pages/ProfileUpdate/[userId].tsx
  42manito/src/styles/profile.css
Labels: fix

#221 [fix]: 본인 카드 프로필에서 멘토링 요청버튼 삭제
  42manito/src/components/Mentor/Modal.tsx
Labels: todo, fix

#230 [feat]: reservation page #223
  42manito/src/components/Reservation/Reservation.tsx
  42manito/src/pages/reservation/[reservationId].tsx
Labels: enhancement

#232 [fix]: 해시태그 잘림 이슈 해소 #231
  42manito/src/components/Mentor/Card.tsx
Labels: bug, fix

#235 [todo] 멘토링 취소 모달 개발
  42manito/src/RTK/Apis/Reservation.ts
  42manito/src/RTK/Slices/Reservation.ts
  42manito/src/Types/General/ButtonType.ts
  42manito/src/Types/Reservations/ReservationPatchCancelReq.dto.ts
  42manito/src/components/Cancel/CancelMessageSelect.tsx
  42manito/src/components/Cancel/CancelModal.tsx
  42manito/src/components/Connect/ConnectModal.tsx
  42manito/src/components/Reservation/Reservation.tsx
  42manito/src/components/Reservation/modal/FeedbackModal.tsx
  42manito/src/pages/Mentorings/index.tsx
  42manito/src/pages/ProfileUpdate/[userId].tsx
  42manito/src/pages/index.tsx
  42manito/src/pages/reservation/[reservationId].tsx
Labels: bug, enhancement, fix

#239 [fix] search 관련 오류 해결 #238
  42manito/src/RTK/Apis/Search.ts
  42manito/src/RTK/Slices/Global.ts
  42manito/src/components/Layout/Header/index.tsx
  42manito/src/components/Search/SearchInput/index.tsx
  42manito/src/hooks/Search/FetchSearch.tsx
  42manito/src/pages/Search/[searchKeyword].tsx
  42manito/src/utils/ObjectToURLString.ts
Labels: fix

#237 [fix] 멘토링 확인 프로세스 변경
  42manito/public/Slack-mark-RGB.png
  42manito/src/RTK/Apis/User.ts
  42manito/src/RTK/Slices/ProfileUpdate.ts
  42manito/src/RTK/Slices/Reservation.ts
  42manito/src/Types/MentorProfiles/MentorProfile.dto.ts
  42manito/src/Types/MentorProfiles/MentorProfilePatchReq.dto.ts
  42manito/src/Types/Users/UserDefault.dto.ts
  42manito/src/components/Profile/Info.tsx
  42manito/src/components/Profile/Toggle.tsx
  42manito/src/components/Profile/UserProfile.tsx
  42manito/src/components/Reservation/NextProgressButton.tsx
  42manito/src/components/Reservation/modal/SocialLinkModal.tsx
  42manito/src/pages/Mentorings/index.tsx
  42manito/src/pages/ProfileUpdate/[userId].tsx
  42manito/src/pages/index.tsx
  42manito/src/pages/reservation/[reservationId].tsx
  42manito/src/styles/profile.css
Labels: enhancement

#240 [Fix] 배너 링크 / 예약 페이지 링크 Pascal Case로 변경
  42manito/src/Types/Banners/Banner.dto.tsx
  42manito/src/components/Banners/Banners.tsx
  42manito/src/components/Banners/TopBanner.tsx
  42manito/src/components/Layout/Footer.tsx
  42manito/src/components/Layout/Header/components/DesktopNav.tsx
  42manito/src/components/Layout/Header/components/Sidebar.tsx
  42manito/src/components/Profile/Update/HashtagUpdateInput.tsx
  42manito/src/pages/Mentorings/index.tsx
  42manito/src/pages/Reservation/[reservationId].tsx
  42manito/src/styles/banner.css
  42manito/src/utils/BaseQuery.ts
Labels: fix

#245 [hotfix] ver 1.0.1
  42manito/src/components/Banners/TopBanner.tsx
Labels: deploy

#246 [fix]: 해시태그 잘림 현상 해소
  42manito/src/components/Mentor/Card.tsx
Labels: fix

#247 [fix]: 해시태그 잘림 현상 해소 (#246)
  42manito/src/components/Mentor/Card.tsx
Labels: deploy

#252 [fix]: gtag 주입 오류
  42manito/env.sample
  42manito/src/pages/_app.tsx
Labels: fix

#253 version 1.0.3
  42manito/env.sample
  42manito/src/pages/_app.tsx
Labels: deploy

#261 version 1.0.4
  42manito/src/components/Connect/ConnectModal.tsx
  42manito/src/components/Mentor/Modal.tsx
  42manito/src/components/Profile/Description.tsx
  42manito/src/components/Profile/Toggle.tsx
  42manito/src/components/Profile/Update/HashtagUpdateInput.tsx
  42manito/src/components/Profile/UserProfile.tsx
  42manito/src/components/Reservation/Reservation.tsx
  42manito/src/components/Reservation/modal/SocialLinkModal.tsx
  42manito/src/pages/ProfileUpdate/[userId].tsx
  42manito/src/styles/profile.css
Labels: deploy

#264 [fix]: fix ttl
  42manito/next.config.js
Labels: emergency, fix

#263 [fix]: cdn 이미지 오류 임시 해결
  42manito/public/default_profile.png
  42manito/src/components/Mentor/Card.tsx
  42manito/src/components/Profile/Image.tsx
  42manito/src/components/Reservation/card/ReservationCard.tsx
  42manito/src/components/Reservation/feedback/FeedbackCard.tsx
Labels: emergency, fix

#266 version 1.0.5
  42manito/next.config.js
  42manito/public/default_profile.png
  42manito/src/components/Mentor/Card.tsx
  42manito/src/components/Profile/Image.tsx
  42manito/src/components/Reservation/card/ReservationCard.tsx
  42manito/src/components/Reservation/feedback/FeedbackCard.tsx
Labels: deploy
