Repository manito42/FrontEnd, pull requests merged in 2023-08, with the labels that each got.

#18 :bug: [HotFix] Add globals.css in storybook preview
  42manito/.storybook/preview.ts
Labels: bug

#19 :sparkles: [Feature] Button Component
  42manito/.yarn/install-state.gz
  42manito/src/common/Button/Button.module.css
  42manito/src/common/Button/Button.stories.tsx
  42manito/src/common/Button/Button.tsx
  42manito/src/common/Button/index.ts
  42manito/src/common/index.ts
Labels: enhancement

#24 :green_heart: [Chore] sonarqube setting
  .github/workflows/sonarqube.yml
  sonar-project.properties
Labels: enhancement

#29 🐛 hotfix: 오타수정
  42manito/src/components/Profile/Categories.tsx
Labels: bug

#61 🐛 bugfix: 토글문제 해결
  42manito/src/components/Profile/Toggle.tsx
Labels: bug

#62 test deploy
  42manito/src/components/Profile/Toggle.tsx
Labels: test deploy

#57 [Bug] MentorProfile 창에서 스크롤이 안올라가는 문제
  42manito/src/components/Categories/CategoriesModal.tsx
Labels: bug

#64 bugfix 후 test deploy
  42manito/src/components/Categories/CategoriesModal.tsx
  42manito/src/hooks/Search/FetchSearch.tsx
Labels: bug

#66 🐛 [bug] 검색시 페이지 초기화 문제
  42manito/src/components/Search/MentorList.tsx
  42manito/src/hooks/Search/FetchSearch.tsx
Labels: bug

#69 54/request/profile/description
  42manito/src/components/Profile/Toggle.tsx
  42manito/src/pages/ProfileUpdate/[userId].tsx
Labels: request, UI/UX

#68 🐛 bugfix: 버튼 고정되는 문제 해결
  42manito/src/components/Profile/Toggle.tsx
Labels: bug

#74 🐛 hotfix: build 에러 해결
  42manito/src/components/Profile/Toggle.tsx
Labels: bug

#75 빌드에러 해결 후 배포테스트
  42manito/src/components/Profile/Toggle.tsx
Labels: test deploy
