Repository manito42/FrontEnd, pull requests merged in 2023-09, with the labels that each got.

#79 Profile UI 변경 및 버그 수정
  42manito/src/RTK/Apis/Category.ts
  42manito/src/RTK/Apis/User.ts
  42manito/src/RTK/Slices/ProfileUpdate.ts
  42manito/src/components/Profile/Categories.tsx
  42manito/src/components/Profile/Description.tsx
  42manito/src/components/Profile/Hashtag.tsx
  42manito/src/components/Profile/HashtagCard.tsx
  42manito/src/components/Profile/Image.tsx
  42manito/src/components/Profile/Info.tsx
  42manito/src/components/Profile/Toggle.tsx
  42manito/src/components/Profile/UserProfile.tsx
  42manito/src/pages/ProfileUpdate/[userId].tsx
Labels: bug, enhancement, UI/UX

#80 [TestDeploy] - #79 병합
  42manito/src/RTK/Apis/Category.ts
  42manito/src/RTK/Apis/User.ts
  42manito/src/RTK/Slices/ProfileUpdate.ts
  42manito/src/components/Profile/Categories.tsx
  42manito/src/components/Profile/Description.tsx
  42manito/src/components/Profile/Hashtag.tsx
  42manito/src/components/Profile/HashtagCard.tsx
  42manito/src/components/Profile/Image.tsx
  42manito/src/components/Profile/Info.tsx
  42manito/src/components/Profile/Toggle.tsx
  42manito/src/components/Profile/UserProfile.tsx
  42manito/src/pages/ProfileUpdate/[userId].tsx
Labels: test deploy

#81 [TestDeploy] deploy after fix
  42manito/src/components/Profile/CategoryCard.tsx
Labels: test deploy

#83 :sparkles: [Feat]: Build Checker
  .github/workflows/build-test.yml
  42manito/.yarnrc.yml
Labels: enhancement

#82 [UI] 프로필 UI 변경 및 버그 해소
  42manito/src/components/Profile/Categories.tsx
  42manito/src/components/Profile/CategoryCard.tsx
  42manito/src/components/Profile/Description.tsx
  42manito/src/components/Profile/Hashtag.tsx
  42manito/src/components/Profile/HashtagCard.tsx
  42manito/src/components/Profile/Toggle.tsx
  42manito/src/components/Profile/UserProfile.tsx
  42manito/src/pages/ProfileUpdate/[userId].tsx
  42manito/src/styles/globals.css
Labels: bug

#86 [TestDeploy] Update #82
  .github/workflows/build-test.yml
  42manito/.yarnrc.yml
  42manito/src/components/Profile/Categories.tsx
  42manito/src/components/Profile/CategoryCard.tsx
  42manito/src/components/Profile/Description.tsx
  42manito/src/components/Profile/Hashtag.tsx
  42manito/src/components/Profile/HashtagCard.tsx
  42manito/src/components/Profile/Toggle.tsx
  42manito/src/components/Profile/UserProfile.tsx
  42manito/src/pages/ProfileUpdate/[userId].tsx
  42manito/src/styles/globals.css
Labels: UI/UX, test deploy

#91 [UI] #87 Profile - Mentor Modal 통합
  42manito/src/RTK/Apis/Hashtag.ts
  42manito/src/RTK/Slices/MentorConnect.ts
  42manito/src/RTK/Slices/ProfileUpdate.ts
  42manito/src/RTK/store.ts
  42manito/src/components/Connect/ConnectModal.tsx
  42manito/src/components/Mentor/CategorySelect.tsx
  42manito/src/components/Mentor/HashtagSelect.tsx
  42manito/src/components/Mentor/Modal.tsx
  42manito/src/components/Profile/Categories.tsx
  42manito/src/components/Profile/CategoryCard.tsx
  42manito/src/components/Profile/Description.tsx
  42manito/src/components/Profile/Hashtag.tsx
  42manito/src/components/Profile/Image.tsx
  42manito/src/components/Profile/Info.tsx
  42manito/src/components/Profile/Update/CategoryUpdateMultiple.tsx
  42manito/src/components/Profile/Update/HashtagUpdateInput.tsx
  42manito/src/components/Profile/UserProfile.tsx
  42manito/src/hooks/Profile/Component.tsx
  42manito/src/hooks/Profile/Page.tsx
  42manito/src/pages/Profile/[userId].tsx
  42manito/src/pages/ProfileUpdate/[userId].tsx
  42manito/src/styles/connect.css
  42manito/src/styles/globals.css
  42manito/src/styles/mentor.css
  42manito/src/styles/profile.css
Labels: enhancement, UI/UX

#92 [TestDeploy] #87 적용
  42manito/src/RTK/Apis/Hashtag.ts
  42manito/src/RTK/Slices/MentorConnect.ts
  42manito/src/RTK/Slices/ProfileUpdate.ts
  42manito/src/RTK/store.ts
  42manito/src/components/Connect/ConnectModal.tsx
  42manito/src/components/Mentor/CategorySelect.tsx
  42manito/src/components/Mentor/HashtagSelect.tsx
  42manito/src/components/Mentor/Modal.tsx
  42manito/src/components/Profile/Categories.tsx
  42manito/src/components/Profile/CategoryCard.tsx
  42manito/src/components/Profile/Description.tsx
  42manito/src/components/Profile/Hashtag.tsx
  42manito/src/components/Profile/Image.tsx
  42manito/src/components/Profile/Info.tsx
  42manito/src/components/Profile/Update/CategoryUpdateMultiple.tsx
  42manito/src/components/Profile/Update/HashtagUpdateInput.tsx
  42manito/src/components/Profile/UserProfile.tsx
  42manito/src/hooks/Profile/Component.tsx
  42manito/src/hooks/Profile/Page.tsx
  42manito/src/pages/Profile/[userId].tsx
  42manito/src/pages/ProfileUpdate/[userId].tsx
  42manito/src/styles/connect.css
  42manito/src/styles/globals.css
  42manito/src/styles/mentor.css
  42manito/src/styles/profile.css
Labels: test deploy

#97 [Fix] #96 Modal 관련 버그 수정
  42manito/src/RTK/Apis/User.ts
  42manito/src/components/Mentor/Modal.tsx
  42manito/src/components/Profile/UserProfile.tsx
  42manito/src/hooks/Profile/Component.tsx
  42manito/src/styles/globals.css
  42manito/src/styles/mentor.css
  42manito/src/styles/profile.css
Labels: bug

#99 [UI] #88 홈 레이아웃 구성 및 MentorCardList UI 변경
  42manito/public/banner.png
  42manito/src/RTK/Apis/Home.ts
  42manito/src/RTK/Slices/Home.ts
  42manito/src/Types/Homes/HomeGetAll.dto.ts
  42manito/src/Types/Homes/HomeGetCategory.dto.ts
  42manito/src/components/Global/CardHashtag.tsx
  42manito/src/components/Global/TopBanner.tsx
  42manito/src/components/Home/CategoryIcon.tsx
  42manito/src/components/Home/CategoryIconList.tsx
  42manito/src/components/Home/MentorList.tsx
  42manito/src/components/Home/ReservationRequests.tsx
  42manito/src/components/Mentor/Card.tsx
  42manito/src/components/Mentor/Modal.tsx
  42manito/src/components/Profile/UserProfile.tsx
  42manito/src/components/Search/SearchInput/index.tsx
  42manito/src/hooks/Home/FetchHome.tsx
  42manito/src/pages/Profile/[userId].tsx
  42manito/src/pages/index.tsx
  42manito/src/styles/banner.css
  42manito/src/styles/cardhashtag.css
  42manito/src/styles/globals.css
  42manito/src/styles/home.css
  42manito/src/styles/mentor.css
  42manito/src/styles/reservation.css
  42manito/src/styles/search.css
Labels: enhancement, UI/UX

#100 [TestDeploy] #88
  42manito/public/banner.png
  42manito/src/RTK/Apis/Home.ts
  42manito/src/RTK/Apis/User.ts
  42manito/src/RTK/Slices/Home.ts
  42manito/src/Types/Homes/HomeGetAll.dto.ts
  42manito/src/Types/Homes/HomeGetCategory.dto.ts
  42manito/src/components/Global/CardHashtag.tsx
  42manito/src/components/Global/TopBanner.tsx
  42manito/src/components/Home/CategoryIcon.tsx
  42manito/src/components/Home/CategoryIconList.tsx
  42manito/src/components/Home/MentorList.tsx
  42manito/src/components/Home/ReservationRequests.tsx
  42manito/src/components/Layout/Footer.tsx
  42manito/src/components/Mentor/Card.tsx
  42manito/src/components/Mentor/Modal.tsx
  42manito/src/components/Profile/UserProfile.tsx
  42manito/src/components/Search/SearchInput/index.tsx
  42manito/src/hooks/Home/FetchHome.tsx
  42manito/src/hooks/Profile/Component.tsx
  42manito/src/pages/Profile/[userId].tsx
  42manito/src/pages/index.tsx
  42manito/src/styles/banner.css
  42manito/src/styles/cardhashtag.css
  42manito/src/styles/globals.css
  42manito/src/styles/home.css
  42manito/src/styles/mentor.css
  42manito/src/styles/profile.css
  42manito/src/styles/reservation.css
  42manito/src/styles/search.css
Labels: test deploy

#102 :bug: [fix]: 이미 예약한 reservation 409 처리를 하지 못하는 문제 수정함.
  42manito/src/components/Mentor/Modal.tsx
  42manito/src/utils/BaseQuery.ts
Labels: bug

#103 :bug: [fix]: modal 관련 문제 해결
  42manito/src/components/Mentor/Modal.tsx
  42manito/src/styles/connect.css
  42manito/src/styles/mentor.css
Labels: bug

#104 :bug: [Fix]: search page 오류 수정 및 UI 개선
  42manito/src/components/Search/MentorList.tsx
  42manito/src/pages/Search/[searchKeyword].tsx
  42manito/src/styles/search.css
Labels: bug

#105 [TestDeploy] 버그 수정 배포
  .github/workflows/build-test.yml
  42manito/src/components/Mentor/Modal.tsx
  42manito/src/components/Search/MentorList.tsx
  42manito/src/pages/Search/[searchKeyword].tsx
  42manito/src/styles/connect.css
  42manito/src/styles/mentor.css
  42manito/src/styles/search.css
  42manito/src/utils/BaseQuery.ts
Labels: test deploy

#108 [UI] fix home
  42manito/src/pages/index.tsx
  42manito/src/styles/home.css
  42manito/src/styles/mentor.css
Labels: enhancement, UI/UX

#109 :fire: [Fix]: 해시태그 클릭시 이동하는 로직 삭제
  42manito/src/components/Profile/Hashtag.tsx
  42manito/src/pages/ProfileUpdate/[userId].tsx
Labels: bug

#110 [UI] 레이아웃 구조 변경 및 전체 색상 제어
  42manito/src/common/Card/Card.module.css
  42manito/src/common/Modal/Modal.module.css
  42manito/src/components/About/About2.tsx
  42manito/src/components/Alert/ErrorAlert.tsx
  42manito/src/components/Alert/InfoAlert.tsx
  42manito/src/components/Categories/CategoriesModal.tsx
  42manito/src/components/Enroll/index.tsx
  42manito/src/components/Feedback/Card.tsx
  42manito/src/components/Home/Typo.tsx
  42manito/src/components/Layout/DarkModeButton.tsx
  42manito/src/components/Layout/Footer.tsx
  42manito/src/components/Layout/Header/components/DrawerContent.tsx
  42manito/src/components/Layout/Header/components/Sidebar.tsx
  42manito/src/components/Layout/Header/index.tsx
  42manito/src/components/Layout/Layout.tsx
  42manito/src/components/Mentor/Card.tsx
  42manito/src/components/Profile/Hashtag.tsx
  42manito/src/components/Profile/Info.tsx
  42manito/src/components/Profile/Toggle.tsx
  42manito/src/components/Search/SearchInput/index.tsx
  42manito/src/pages/Categories/index.tsx
  42manito/src/pages/Feedback/Index.tsx
  42manito/src/pages/Profile/[userId].tsx
  42manito/src/pages/ProfileUpdate/[userId].tsx
  42manito/src/pages/Ranking/index.tsx
  42manito/src/pages/Search/[searchKeyword].tsx
  42manito/src/pages/index.tsx
  42manito/src/styles/cardhashtag.css
  42manito/src/styles/connect.css
  42manito/src/styles/globals.css
  42manito/src/styles/home.css
  42manito/src/styles/layout.css
  42manito/src/styles/mentor.css
  42manito/src/styles/profile.css
  42manito/src/styles/reservation.css
  42manito/src/styles/search.css
  42manito/tailwind.config.js
Labels: UI/UX

#113 :bug: [Fix]: Profile Update 시 버그 해소
  42manito/src/RTK/Apis/User.ts
  42manito/src/pages/ProfileUpdate/[userId].tsx
Labels: bug

#114 [UI/Refactor] Header 요소 위치 변경
  42manito/src/components/Layout/Header/components/Sidebar.tsx
  42manito/src/components/Layout/Header/index.tsx
  42manito/src/components/Layout/Layout.tsx
  42manito/src/components/Search/MentorList.tsx
  42manito/src/hooks/Home/FetchHome.tsx
  42manito/src/pages/Search/[searchKeyword].tsx
  42manito/src/pages/index.tsx
  42manito/src/styles/globals.css
  42manito/src/styles/layout.css
  42manito/src/styles/mentor.css
  42manito/src/styles/search.css
Labels: UI/UX

#115 [UI] login button
  42manito/src/components/Layout/Header/index.tsx
  42manito/src/components/Mentor/Modal.tsx
  42manito/src/styles/layout.css
Labels: UI/UX

#116 :lipstick: [Feat]: 로그인 시 로딩창
  42manito/src/components/Global/Loading.tsx
  42manito/src/components/Layout/Header/index.tsx
  42manito/src/hooks/Home/FetchHome.tsx
  42manito/src/styles/globals.css
  42manito/src/styles/loading.css
Labels: enhancement, UI/UX

#119 :lipstick: [UI]: Banner
  42manito/public/guide.png
  42manito/src/components/Global/TopBanner.tsx
  42manito/src/pages/Guide/index.tsx
  42manito/src/pages/index.tsx
  42manito/src/styles/banner.css
Labels: UI/UX

#126 :sparkles: [Feat]: ReservationRequests, ReservationCard
  42manito/src/RTK/Apis/Reservation.ts
  42manito/src/RTK/store.ts
  42manito/src/Types/Reservations/ReservationDefault.dto.ts
  42manito/src/Types/Reservations/ReservationStatus.ts
  42manito/src/Types/UserReservation/UserReservationReqDto.ts
  42manito/src/Types/UserReservation/UserReservationResDto.ts
  42manito/src/components/Enroll/components/Card.tsx
  42manito/src/components/Enroll/components/buttons/AcceptButton.tsx
  42manito/src/components/Enroll/components/buttons/CancelButton.tsx
  42manito/src/components/Enroll/components/buttons/doneButton.tsx
  42manito/src/components/Enroll/components/buttons/menteeFeedbackButton.tsx
  42manito/src/components/Enroll/index.tsx
  42manito/src/components/Home/Reservation/ReservationRequests.tsx
  42manito/src/components/Home/ReservationRequests.tsx
  42manito/src/components/Mentor/Card.tsx
  42manito/src/components/Mentor/Modal.tsx
  42manito/src/components/Reservation/ReservationCard.tsx
  42manito/src/pages/index.tsx
  42manito/src/styles/cardhashtag.css
  42manito/src/styles/globals.css
  42manito/src/styles/mentor.css
  42manito/src/styles/reservation.css
Labels: enhancement, UI/UX

#132 [Feat] reservation - 멘토링 관리 페이지
  42manito/src/RTK/Apis/Reservation.ts
  42manito/src/RTK/Slices/Global.ts
  42manito/src/RTK/Slices/Reservation.ts
  42manito/src/RTK/rootReducer.ts
  42manito/src/Types/General/IPaginationInfo.ts
  42manito/src/Types/General/IPaginationResponse.ts
  42manito/src/Types/Hashtags/HashtagGetRes.dto.ts
  42manito/src/Types/MenteeFeedbacks/MenteeFeedbackGetRes.dto.ts
  42manito/src/Types/MentorProfiles/MentorProfileGetRes.dto.ts
  42manito/src/Types/Reservations/ReservationDefault.dto.ts
  42manito/src/Types/Reservations/ReservationGetReq.dto.ts
  42manito/src/Types/Reservations/ReservationGetRes.dto.ts
  42manito/src/Types/Reservations/ReservationPatchMenteeCheckReq.dto.ts
  42manito/src/Types/Reservations/ReservationRole.ts
  42manito/src/common/Modal/Modal.module.css
  42manito/src/components/Categories/CategoriesModal.tsx
  42manito/src/components/Home/Reservation/ReservationRequests.tsx
  42manito/src/components/Layout/Header/components/Sidebar.tsx
  42manito/src/components/Layout/Header/index.tsx
  42manito/src/components/Mentor/Card.tsx
  42manito/src/components/Mentor/Modal.tsx
  42manito/src/components/Profile/Hashtag.tsx
  42manito/src/components/Profile/Toggle.tsx
  42manito/src/components/Profile/Typo.tsx
  42manito/src/components/Profile/Update/Update.tsx
  42manito/src/components/Reservation/NextProgressButton.tsx
  42manito/src/components/Reservation/Reservation.tsx
  42manito/src/components/Reservation/ReservationLists.tsx
  42manito/src/components/Reservation/card/ReservationCard.tsx
  42manito/src/components/Reservation/getReservationStatus.ts
  42manito/src/components/Reservation/modal/ReservationModal.tsx
  42manito/src/hooks/Profile/Page.tsx
  42manito/src/pages/Mentorings/index.tsx
  42manito/src/pages/index.tsx
  42manito/src/styles/globals.css
  42manito/src/styles/mentor.css
  42manito/src/styles/mentorings.css
  42manito/src/styles/reservation.css
  42manito/src/utils/ObjectToURLString.ts
Labels: enhancement, UI/UX

#135 [fix] profile #134
  42manito/src/components/Profile/Description.tsx
  42manito/src/components/Profile/Info.tsx
  42manito/src/components/Profile/Toggle.tsx
  42manito/src/components/Profile/Update/HashtagUpdateInput.tsx
  42manito/src/components/Profile/UserProfile.tsx
  42manito/src/pages/Profile/[userId].tsx
  42manito/src/pages/ProfileUpdate/[userId].tsx
Labels: bug

#137 [fix]: mentor card 사이즈 변경 및 description 잘리는 문제 해소
  42manito/src/components/Home/MentorList.tsx
  42manito/src/pages/index.tsx
  42manito/src/styles/mentor.css
Labels: bug

#147 [fix] login logout #144
  42manito/env.sample
  42manito/src/components/Layout/Header/index.tsx
  42manito/src/styles/layout.css
Labels: fix

#148 [feat] feedback modal #146
  42manito/src/RTK/Apis/Reservation.ts
  42manito/src/RTK/Slices/Reservation.ts
  42manito/src/Types/Reservations/ReservationDefault.dto.ts
  42manito/src/components/Connect/ConnectModal.tsx
  42manito/src/components/Feedback/Card.tsx
  42manito/src/components/Reservation/NextProgressButton.tsx
  42manito/src/components/Reservation/Reservation.tsx
  42manito/src/components/Reservation/feedback/FeedbackCard.tsx
  42manito/src/components/Reservation/getReservationStatus.ts
  42manito/src/components/Reservation/modal/FeedbackModal.tsx
  42manito/src/pages/Mentorings/index.tsx
  42manito/src/pages/index.tsx
  42manito/src/styles/connect.css
  42manito/src/styles/mentor.css
  42manito/src/styles/reservation.css
Labels: enhancement

#142 Fix/배너수정 #141
  42manito/src/components/Banners/Banners.tsx
  42manito/src/components/Banners/TopBanner.tsx
  42manito/src/styles/banner.css
Labels: fix

#182 [fix] title 오탈자 수정 및 darkmode 강제
  42manito/src/components/Layout/Footer.tsx
  42manito/src/pages/_app.tsx
Labels: fix

#186 [fix] 로딩, 카테고리 아이콘 이슈 수정
  42manito/src/components/Loading/index.tsx
  42manito/src/pages/SignIn/index.tsx
  42manito/src/styles/home.css
Labels: fix

#187 [fix]: 오탈자 수정
  42manito/src/components/Reservation/Reservation.tsx
Labels: fix

#213 [fix] 멘토링 feedback 별점 기본값을 5점으로 변경
  42manito/src/components/Reservation/modal/FeedbackModal.tsx
Labels: fix

#212 [fix] ProfileUpdate에서의 소개글 글자수 제한 수정
  42manito/src/pages/ProfileUpdate/[userId].tsx
Labels: fix

#215 [todo] About Page 제거
  42manito/src/components/About/About1.tsx
  42manito/src/components/About/About2.tsx
  42manito/src/components/About/About3.tsx
  42manito/src/components/About/About4.tsx
  42manito/src/components/About/About5.tsx
  42manito/src/components/About/Cursor.tsx
  42manito/src/components/About/useAnimaitonState.tsx
  42manito/src/components/Layout/Header/components/Sidebar.tsx
  42manito/src/pages/About/index.tsx
Labels: todo, fix

#211 [fix] tag search #191
  42manito/src/components/Global/CardHashtag.tsx
  42manito/src/components/Mentor/Card.tsx
  42manito/src/components/Profile/Categories.tsx
  42manito/src/components/Profile/CategoryCard.tsx
  42manito/src/components/Profile/Description.tsx
  42manito/src/components/Profile/Hashtag.tsx
  42manito/src/components/Profile/HashtagCard.tsx
  42manito/src/components/Profile/Typo.tsx
  42manito/src/components/Profile/Update/CategoryUpdateMultiple.tsx
  42manito/src/components/Profile/Update/Update.tsx
  42manito/src/components/Profile/UserProfile.tsx
  42manito/src/components/Reservation/Reservation.tsx
  42manito/src/pages/Profile/[userId].tsx
  42manito/src/pages/ProfileUpdate/[userId].tsx
  42manito/src/styles/cardhashtag.css
  42manito/src/styles/mentor.css
  42manito/src/styles/profile.css
  42manito/src/styles/reservation.css
Labels: fix
